trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release
  projectPath: src/AzPipelinesDemo.csproj

steps:
- task: UseDotNet@2
  displayName: Use .NET 9 SDK
  inputs:
    packageType: sdk
    version: 9.x

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(projectPath)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(projectPath)
    arguments: --configuration $(buildConfiguration) --no-restore

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(projectPath)
    arguments: --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: Container
